spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: irlen
    url: jdbc:mysql://10.0.0.99:3306/sell?characterEncoding=utf-8&useSSL=false
    type: com.mchange.v2.c3p0.ComboPooledDataSource
  jpa:
    show-sql: true
  logging:
    level:
      com.irlen.mapper: trace
